route:
  group_by: ['alertname']
  group_interval: '1h'
  repeat_interval: '4h'
  receiver: 'webhook'
receivers:
- name: 'webhook'
  webhook_configs:
    - send_resolved: true
      url: 'http://duty-ci.taozeyu.com:3006/prometheus'