global:
  resolve_timeout: 2m
  wechat_api_url: 'https://qyapi.weixin.qq.com/cgi-bin/'
  wechat_api_secret: '0LkP8OLiz-iWgTSyDTeMHdbmT0CpYbGuS1tdbJidJ2o'
  wechat_api_corp_id: 'ww6da1371aed8c474f'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'wechat'
receivers:
- name: 'wechat'
  wechat_configs:
  - send_resolved: true
    to_party: 'CI'
    agent_id: '1000004'